### PR TITLE
Added README and CONTRIBUTING info

### PR DESCRIPTION
**Pull request by nebrius**
Added a mission statement and other information to the README, and added some basic info to the CONTRIBUTING guide.

### CODE REVIEW

**Comment by tmpvar** [comment]
looks good :+1:

**Comment by noopkat** [comment]
:+1:

**Comment by voodootikigod** [comment]
:+1:

_Chris Williams_

@voodootikigod http://twitter.com/voodootikigod | GitHub
http://github.com/voodootikigod

_The things I make that you should check out:_
SaferAging http://www.saferaging.com/ | JSConf http://jsconf.com/ |
RobotsConf http://robotsconf.com/ | RobotsWeekly
http://robotsweekly.com/

Help me end the negativity on the internet, share this
http://jsconf.eu/2011/an_end_to_negativity.html.

**Comment by nebrius** [comment]
So here's some fortuitous timing: https://github.com/nodejs/diversity/pull/7

Looks like there's some work going on higher up the chain as far as working groups go, so might as well take all of that into play here as well.

**Comment by nebrius** [comment]
I added a lot more info, sourced from various places around the node repos as well as from comments in Gitter. Let me know what you think!

**Comment by dtex** [comment]
Contributing looks perfect.

I have two thoughts on the readme: 

> The whole ethos behind NodeBots is to make working with hardware accessible for everyone.

We use the word "NodeBots" and assume that readers will know what that is. I'm not even sure we all agree on a formal definition. The tagline over at nodebots.io reads "Robots powered by JavaScript", but we build an awful lot of things in nodebots-land that many people would not consider to be "robots". It's kind of hard to define so maybe we should just say "The whole ethos behind this group..." because "The Node.js Hardware Working Group" is probably as clear and concise as we are going to get. 

> We focus on difficulties that users encounter when consuming common hardware libraries, primarily [Johnny-Five](http://johnny-five.io/), and difficulties that developers encounter when creating and distributing these libraries.

Naturally we all lean towards Johnny-Five (duh, because it's the best) but explicitly mentioning and prioritizing Johnny-Five suggests a bias. It's not even something the group is directly concerned with. 

We should be focused on lower level modules that make communication with hardware easier and better, things like serialport, noble, etc. We have our spreadsheet of hardware modules working, I propose that we create a subset of modules that fit in that category. Those are the modules we should be calling out.

**Comment by nebrius** [comment]
Any final comments before we merge this?

**Comment by Resseguie** [comment]
LGTM @nebrius

**Comment by joshperry** [comment]
Great work, @nebrius. #shipit!

**Comment by nebrius** [comment]
Done and done!
@mikeal, can you or someone else make sure that the following people are added as collaborators? I don't have the ability to add them myself.
- Donovan Buck (@dtex)
- Francis Gulotta (@reconbot)
- Suz Hinton (@noopkat)
- Joshua Perry (@joshperry)
- David Resseguie (@Resseguie)

**Pull request merged**
